# Generated by Django 5.1.5 on 2025-01-22 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Admin", "0003_tbl_place"),
    ]

    operations = [
        migrations.CreateModel(
            name="tbl_sub_category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sub_category", models.CharField(max_length=30)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Admin.tbl_category",
                    ),
                ),
            ],
        ),
    ]
