# Generated by Django 5.1.5 on 2025-01-23 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Admin", "0004_tbl_sub_category"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="tbl_sub_category",
            new_name="tbl_subcategory",
        ),
        migrations.RenameField(
            model_name="tbl_subcategory",
            old_name="sub_category",
            new_name="subcategory_name",
        ),
    ]
