# Generated by Django 5.1.5 on 2025-01-27 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Admin", "0006_tbl_admin"),
    ]

    operations = [
        migrations.CreateModel(
            name="tbl_user",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=30)),
                ("user_email", models.CharField(max_length=50)),
                ("user_password", models.CharField(max_length=30)),
                ("user_gender", models.CharField(max_length=15)),
                ("user_contact", models.CharField(max_length=30)),
                ("user_address", models.CharField(max_length=150)),
                (
                    "user_photo",
                    models.FileField(upload_to="Assets/user/photo", verbose_name=""),
                ),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Admin.tbl_district",
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Admin.tbl_place",
                    ),
                ),
            ],
        ),
    ]
