# Generated by Django 5.1.5 on 2025-02-01 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Guest", "0002_remove_tbl_user_district_alter_tbl_user_user_photo"),
    ]

    operations = [
        migrations.CreateModel(
            name="tbl_newuser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=30)),
                ("user_email", models.CharField(max_length=70)),
                ("user_password", models.CharField(max_length=30)),
            ],
        ),
    ]
