# Generated by Django 5.1.5 on 2025-01-29 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Guest", "0002_remove_tbl_user_district_alter_tbl_user_user_photo"),
    ]

    operations = [
        migrations.CreateModel(
            name="tbl_mystatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mystatus_age", models.CharField(max_length=10)),
                ("mystatus_height", models.CharField(max_length=10)),
                ("mystatus_weight", models.CharField(max_length=10)),
                ("mystatus_bloodgroup", models.CharField(max_length=10)),
                ("mystatus_bmi", models.CharField(max_length=10)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Guest.tbl_user"
                    ),
                ),
            ],
        ),
    ]
