# Generated by Django 5.1.5 on 2025-01-30 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Guest", "0002_remove_tbl_user_district_alter_tbl_user_user_photo"),
        ("User", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="tbl_complaint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comp_subject", models.CharField(max_length=100)),
                ("comp_details", models.CharField(max_length=500)),
                ("comp_date", models.DateField(auto_now_add=True)),
                ("comp_reply", models.CharField(max_length=500, null=True)),
                ("comp_reply_date", models.DateField(auto_now_add=True)),
                ("comp_status", models.IntegerField(default=0)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Guest.tbl_user"
                    ),
                ),
            ],
        ),
    ]
