# Generated by Django 5.1.5 on 2025-01-30 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0002_tbl_complaint"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tbl_complaint",
            name="comp_reply_date",
            field=models.DateField(null=True),
        ),
    ]
